### ISSUE TITLE
怎么编译?

### ISSUE THREAD

**Issue by shownb** [44670/FBrowser#1]
google一翻,还是不会编译

**Comment by 44670** [comment]
如果已经编译好了qtwebkit，可以直接`mkdir build;cd build;cmake ..;make`

如果没有的话需要编译先编译好qt及所有的依赖库，推荐用buildroot。

**Comment by shownb** [comment]
编译的确挺神经的，qtwebkit是从你的另外一个GitHub获取的，编译成功，但qtwebsockets就失败了，换了几个5。x版本的都不行。

把Web sockets server去了，pc编译成功了
这个把怎么支持websockets客户端功能？

**Comment by 44670** [comment]
是的，编译会比较痛苦。
44670/qtwebkit已经包含了移植到riscv所需的全部patch。

webkit自带websocket客户端功能，qtwebsockets是用于实现远程管理服务端的，去掉后不影响客户端功能。

**Comment by shownb** [comment]
我看启动程序好像也没有./FBrowser --platform linuxfb 为什么直接就可以用fb的。另外，jsbridge好像也没用到？这个可以再优化一下，让他占用的内存少点吗？我想把这个当作gui，那就不用死那么多脑细胞了。只需要配合wsclient来用，写html和js就可以了
谢谢回复

**Comment by 44670** [comment]
因为我编译qt的时候选择了默认linuxfb后端。
如果编译的时候没有这么设置的话，需要设置QT_QPA_PLATFORM环境变量。
jsbridge目前还没用到。
目前的内存占用应该是比较小的了，如果想更小的话感觉可以从字体下手。

**Comment by shownb** [comment]
鉴于编译一次buildroot时间非常的长，完全对交叉编译不懂，伸手党再次发问：怎么把44670/qtwebkit放进buildroot编译？发现韦东山老师的https://gitee.com/weidongshan/neza-d1-buildroot 里面的packages qt5里面也有一个qtwebkit，但和44670/qtwebkit的结构又不一样，不知道怎么办。只好再次请教

**Comment by 44670** [comment]
buildroot目前的那个qtwebkit是不支持riscv的，可以用BR2_PACKAGE_OVERRIDE_FILE重定向到我的qtwebkit。

**Comment by shownb** [comment]
手上的panel86终于到手，搞了个debian的镜像，用
```bash
sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev qt5-qmake cmake
git clone https://github.com/44670/fbrowser
cd fbrowser
mkdir build;cd build;cmake ..;make
./FBrowser --platform linuxfb
```
可以运行。但是tslib却搞不定。不能触摸，想问一下FBrowser是用tslib的还是用libinput的？

**Comment by shownb** [comment]
go写的程序，目前想法是go做一个ws服务端，然后FBrowser连到这个ws，然后FBrowser的页面做gui。
不知道有没有优雅或者高效的方法呢？

**Comment by 44670** [comment]
我觉得这种设计蛮好，go很容易跨平台编译。
